#include<stdio.h>
main()
{
	printf("\t\t-\t-\t-\t-\t-\t\n");
	printf("\t|\t\t\t\t\t\t|\t\n");
	printf("\t|\t\t\t\t\t\t|\t\n");
	printf("\t|\t\t\tNAME\t\t\t|\t\n");
	printf("\t|\t\t\t\t\t\t|\t\n");
	printf("\t|\t\t\t\t\t\t|\t\n");
	printf("\t\t-\t-\t-\t-\t-\t\n");				
}
s
